### ISSUE TITLE
Need delete

### ISSUE THREAD

**Issue by katana2w** [jrop/nedb-promise#3]

**Comment by jrop** [comment]
Hi @katana2w, could you elaborate on this issue please?  A title that short is hardly anything to go on.

**Comment by ianwalter** [comment]
@jrop This doesn't seem to work for me:
```js
// Delete all
db.remove({}, { multi: true });
```

**Comment by jrop** [comment]
@ianwalter That is by design and is done by `nedb` itself (I imagine for speed purposes, so that it doesn't have to rewrite the whole file, a delete operation can just be persisted via appending one line to the data file).  If you wish to compact the data file, you can do so manually: [See the section on nedb's README.md that pertains to this](https://github.com/louischatriot/nedb#persistence).

**Comment by jrop** [comment]
@ianwalter Also, even though that line is added to the file, if you run `db.find({})`, it should return correct data.

**Comment by ianwalter** [comment]
@jrop Ah gotcha, should've RTFM. Thanks!

**Comment by jrop** [comment]
Closing
